Refactor CI configuration for improved clarity and efficiency
- Simplified branch specification for push and pull request triggers.
- Added job names for better readability in CI logs.
- Introduced a new job to check if all previous jobs passed, enhancing CI reliability.
- Set timeout limits for jobs to prevent long-running processes.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,14 +1,9 @@
 name: CI
 on:
   push:
-    branches:
-      - main
+    branches: [main]
   pull_request:
-    branches:
-      - main
-  merge_group:
-    types:
-      - checks_requested
+    branches: [main]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -16,7 +11,9 @@ concurrency:
 
 jobs:
   lint-and-typecheck:
+    name: lint-and-typecheck
     runs-on: ubuntu-latest
+    timeout-minutes: 15
 
     steps:
       - name: Checkout
@@ -32,7 +29,9 @@ jobs:
         run: yarn typecheck
 
   js-tests:
+    name: js-tests
     runs-on: ubuntu-latest
+    timeout-minutes: 15
 
     steps:
       - name: Checkout
@@ -53,6 +52,7 @@ jobs:
           fail_ci_if_error: false
 
   android-build:
+    name: android-build
     runs-on: ubuntu-latest
     timeout-minutes: 60
 
@@ -116,6 +116,7 @@ jobs:
           yarn turbo run build:android --cache-dir="${{ env.TURBO_CACHE_DIR }}"
 
   ios-build:
+    name: ios-build
     runs-on: macos-latest
     timeout-minutes: 60
 
@@ -175,4 +176,21 @@ jobs:
       - name: Build example for iOS
         run: |
           yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}"
+
+  all-checks-passed:
+    name: all-checks-passed
+    runs-on: ubuntu-latest
+    needs: [lint-and-typecheck, js-tests, android-build, ios-build]
+    if: always()
+    steps:
+      - name: Check all jobs passed
+        run: |
+          if [[ "${{ needs.lint-and-typecheck.result }}" != "success" || \
+                "${{ needs.js-tests.result }}"          != "success" || \
+                "${{ needs.android-build.result }}"     != "success" || \
+                "${{ needs.ios-build.result }}"         != "success" ]]; then
+            echo "One or more required checks failed."
+            exit 1
+          fi
+          echo "All checks passed."
 
